### PR TITLE
fix: support move pages on StrictMode

### LINKED ISSUE #116: Arrows (and navigation) not working in React.StrictMode
I'm using react-reader for my project, but arrows do not allow to get to another page of the book. Epub seems to be working fine, you can get to different places using chapters at the beginning of the book. Does anyone have any idea why that is going on?

### PR DESCRIPTION
**Pull request by azu**
Call `book.destroy()` when componentWillUnmount

https://user-images.githubusercontent.com/19714/189505971-d02f7f52-2b5e-47f8-9ef7-fdb04c67102c.mp4

React 18 + Strict Mode does mount → unmount → mount in develop mode.

> With Strict Mode starting in React 18, whenever a component mounts in development, React will simulate immediately unmounting and remounting the component:
> [Strict Mode – React](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state)

EpubView should call `book.destroy()` on `componentWillUnmount`.

fix #116

### CODE REVIEW

File: src/modules/EpubView/EpubView.js [hunk 1]
```diff
@@ -44,6 +44,9 @@ class EpubView extends Component {
   }
 
   componentWillUnmount() {
+    if (this.book) {
+      this.book.destroy()
+    }
     this.book = this.rendition = this.prevPage = this.nextPage = null
```
Comment (azu) [inline src/modules/EpubView/EpubView.js:50]: Previously, `initBook` can not call `destroy()` because `this.book = null` on `componentWillUnmount`.

```js
  initBook() {
    const { url, tocChanged, epubInitOptions } = this.props
    if (this.book) {
      this.book.destroy()
    }
```

**Comment by gerhardsletten** [comment]
@azu Thanks!
